### ISSUE TITLE
Indicator fails ungracefully if python module is not present

### ISSUE THREAD

**Issue by maxhebditch** [maxhebditch/batchgit#5]
When running batchgit -i on a test bed, it fails if the python package `pygtk` is not available. This is to be expected but if the script could test for the presence of pygtk and then fail in a more informative manner this would be good.

Simultaneously I'd prefer it if the script was kept modular in order to allow users not to install `pygtk` if they don't require it, i.e. if they are running the script in CLI only.

**Comment by ga7g08** [comment]
I've fixed the first issue. I think that the primary dependency should be `python-appindicator` since this installs `python-gobject` and hence `pygtk`, but there is relevant tests for all now. 

As for making it modular I think it already is in some sense. At the moment you could install `batchgit` and use it without ever caring about the `-i` flag. The overhead however is that they will have the `indicator.py` and Icons (~20Kb) on their system. 

The issue I guess is that maybe we are trying to solve different problems. `batchgit` is about CLI to do batch operations with `git`, while I made the indicator to use some of the functionality of batchgit to status check several repo's. 

As the author of this work I'll leave the decision to you: I could continue to develop the indicator as part of batchgit, or split them into two projects probably having `batchgit` as a dependency for the indicator. 

Personally I think this second way better follows the  UNIX principle of doing one thing really well.

**Comment by maxhebditch** [comment]
Nice one! 

Still comes out with this error though 

    /$HOME/$USER/batchgit/indicator/indicator.py:115: Warning: /tmp/buildd/glib2.0-2.36.4/./gobject/gsignal.c:2475: signal `child-added' is invalid for instance `0x231f0d0' of type `GtkMenu'
    self.ind.set_menu(menu)

Is there a way to pipe errors to /dev/null like in bash?

Yes sorry, didn't think I made my self clear. I am happy with the modularity of the code as it is.
The icons are not a massive overhead. They could be safely deleted if the `-i` flag is not used.

I would like to keep batchgit in the main script but its up to you if you want to spin the indicator out.

**Comment by ga7g08** [comment]
Okay, I think I will remove it and have it as a separate project. Sorry for dirtying the code-base! Originally it was supposed to be a lightweight addition, but the more I think about it is very separate from `batchgit`. Additionally as you have found - my implementation will not work on any machine (in particular I have no idea if it will work with Mac/Windows). 

I'll wait for a reply before deleting it from main in case you are adamant! Btw I still intend to continue using and hopefully contributing to this project!

**Comment by maxhebditch** [comment]
OK if you are sure. Shall I leave the `-i` flag in or will you be running it a different way? I'd want to keep the two as interoperable as possible?

**Comment by ga7g08** [comment]
It will just be a python program. So once properly installed should just be called and it will start the indicator. I will continue to use `~/.batchgitrc` to source the git repo's etc. 

As for `batchgit`, if you could leave the `-i` flag then if it is installed it just runs, if not maybe point to some instructions how to install? That would be awesome for me as it would run the same, but remain separate entities with a small overhead of having to source two different programs.

**Comment by maxhebditch** [comment]
Hey, yeah no problem. Want to keep the two tied because I think the indicator is really cool. I'll leave you on as a contributor so you can make any changes necessary to get the two running nicely together.
